######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 3 17:50:35 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += thread
LIBS += -lqextserialport
# Input
HEADERS += prog8051.h progThread.h
FORMS += prog8051.ui
SOURCES += main.cpp prog8051.cpp progThread.cpp

unix:DEFINES   = _TTY_POSIX_
win32:DEFINES  = _TTY_WIN_ QWT_DLL QT_DLL
